### ISSUE TITLE
GLU fails when no cuts are specified

### ISSUE THREAD

**Issue by edbennett** [RJHudspith/GLU#1]
When running GLU with no cuts specified (which the documentation indicates should be possible?), the log indicates

```
[IO] Defaulting to no cutting
[INPUT] error reading input file test
```

Looking at the source, this is because on line 389 of `src/IO/input_reader.c`, immediately after saying that GLU will default to no cutting, it then returns `GLU_FAILURE`, which appears to indicate a fatal error. I think this should be a `return GLU_SUCCESS` instead?

**Comment by RJHudspith** [comment]
Hey ed,

Thanks for the issue. I guess you are correct that the code does suggest that this should be possible; having a no-cutting option. My most-recent push addresses this in a bit more detail.

As you can probably see, the input file reading is very clunky. As one must specify options even if that code path is never visited, for instance having to specify a CUTTYPE even if MODE != CUTTING . This is certainly something I have considered changing.

The "cuts" part of this code: Gluon Propagators, Gluon 3pt functions, Topological susceptibility ... etc. Are all very old (mostly written during my Phd) and the design of code's logic is certainly not what I would do now.

Best,
Jamie

**Comment by edbennett** [comment]
Thanks for the lightning-fast review and the additional detail Jamie—my primary use for GLU to date is for converting configurations (as it's the best tool for this that I've found), so my main aim was to find the minimal input file that does nothing other than check the checksum and write out the read configuration in a new format.

**Comment by RJHudspith** [comment]
No worries, this is what I find myself using the code for more-and-more. Well, that and fixing the gauge. Try (to convert a HIREP-format file to a "NERSC_GAUGE", so top 2 rows in SU(3) config):

> ./GLU -i input_file -c {HIREP config} -o {Path to new NERSC_GAUGE config}

With input file below

Information on the output types supported can be found by
> ./GLU --help=STORAGE
or
> ./GLU --help=HEADER
for input. I support more input file types than output file types.

MODE = DEFAULT
HEADER = HIREP
	DIM_0 = 4
	DIM_1 = 4
	DIM_2 = 4
	DIM_3 = 8
CONFNO = 400
RANDOM_TRANSFORM = NO
SEED = 0
GFTYPE = COULOMB
     	GF_TUNE = 0.09
	ACCURACY = 14
	MAX_ITERS = 650
CUTTYPE = PORP
	FIELD_DEFINITION = LINEAR
	MOM_CUT = CYLINDER_CUT
	MAX_T = 7
	MAXMOM = 4
	CYL_WIDTH = 2.0
	ANGLE = 60
	OUTPUT = ./
SMEARTYPE = APE
	DIRECTION = ALL
	SMITERS = 100
	ALPHA1 = 0.6
	ALPHA2 = 0.4
	ALPHA3 = 0.2
U1_MEAS = U1_RECTANGLE
	U1_ALPHA = 0.07957753876221914
	U1_CHARGE = -1.0
CONFIG_INFO = 2+1DWF_b2.25_TEST
	STORAGE = NERSC_GAUGE
BETA = 6.0
        ITERS = 1500
	MEASURE = 1
	OVER_ITERS = 4
	SAVE = 25
	THERM = 100
